### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kythyria** [kythyria/payday2-tools-rust#1]
* [x] #5
* [x] #6 
* [ ] Blender addon
  * [ ] Handle joints better/at all
  * [ ] #7
  * [ ] Parse .material files.
  * [ ] Handle animations
  * [ ] Export all of the above
* [ ] Read and write more formats:
  * [ ] #3
  * [ ] Diesel fonts (include a thing to rasterise?)
  * [ ] BMFont (and conversion to DDS?)
  * [ ] Anything else Luffy already did in [DieselEngineFormats](https://github.com/Luffyyy/DieselEngineFormats/)
* [ ] Properly read and write non-binary scriptdata
  * [ ] custom_xml
  * [ ] generic_xml
  * [ ] #4
* [ ] Update README
